
                      
         ;************************************************************            
                             ;various  light patterns.
                            ;written by achala samapriya
                             ;started on 2006/04/08  
        ;**************************************************************

            	processor PIC16F84A    	;Set the processor
   				radix hex              	;Set the radix
			   	#include <p16F84A.inc> 	;Include header file
		__CONFIG _RC_OSC & _PWRTE_OFF & _CP_OFF & _WDT_OFF
        
       ERRORLEVEL -302
Start   		ORG 0x00

INDEX EQU 0X0C                     ; MOMORY LOCATIONS
LROOM EQU 0X0D
HROOM EQU 0X0E
COMP  EQU 0X0F 
MAP   EQU 0X10
   GOTO MAIN

MAIN
   BANKSEL TRISA
   CLRF TRISA
   CLRF TRISB
   BANKSEL PORTA
   CLRF PORTA                     ;SET BOTH AS OUT PUTS
   CLRF PORTB

LVE
   MOVLW 0X03               
   MOVWF INDEX
L_RUN
      BCF STATUS,C                ;RUNS LEFT
      MOVLW 0X01
      MOVWF PORTB
      CALL DELAY2
ROT   RLF PORTB,1
      CALL DELAY2
      BTFSS PORTB,7     
      GOTO ROT 
      GOTO ECS
ECS   BCF  STATUS,C
      DECFSZ INDEX,1
      GOTO L_RUN
      GOTO RVE
   

RVE
   MOVLW 0X03
   MOVWF INDEX
   
R_RUN
      BCF STATUS,C 
      MOVLW 0X80
      MOVWF PORTB
      CALL DELAY2             ;RUNS RIGHT      
RRT   RRF PORTB,1
      CALL DELAY2      
      BTFSS PORTB,0    
      GOTO RRT 
      GOTO RCS
RCS   BCF  STATUS,C
      DECFSZ INDEX,1
  
      GOTO R_RUN
      GOTO KNT
   
KNT
   MOVLW 0X03                  ; BOTH DERECTIONS
   MOVWF INDEX
KL_RUN
       BCF STATUS,C
       MOVLW 0X01
       MOVWF PORTB
       CALL DELAY2
KROT   RLF PORTB,1
       CALL DELAY2
       BTFSS PORTB,7     
       GOTO KROT 
       GOTO KECS
KECS   BCF  STATUS,C
       GOTO KR_RUN
          
KR_RUN
       BCF STATUS,C
       MOVLW 0X80
       MOVWF PORTB
       CALL DELAY2
KRRT   RRF PORTB,1
       CALL DELAY2
       BTFSS PORTB,0    
       GOTO KRRT 
       GOTO KRCS
KRCS   BCF  STATUS,C
       DECFSZ INDEX,1
       GOTO KL_RUN
       GOTO FRILL
       
       
FRILL

   MOVLW 0X03
   MOVWF INDEX
F1                            ;FILL EFFECT
   MOVLW 0X00
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X01
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X03
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0X07
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X0F
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X1F
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X3F
   MOVWF PORTB
   CALL DELAY2
   
   MOVLW 0X7F
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XFF
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XFE
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0XFC
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XF8
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XF0
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XE0
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0XC0
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0X80
   MOVWF PORTB
   CALL DELAY2 
   CLRF PORTB
   CALL DELAY2
   MOVLW 0X80
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XC0
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XE0
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XF0
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0XF8
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XFC
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XFE
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XFF
   MOVWF PORTB
   CALL DELAY2    
   MOVLW 0X7F
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0X3F
   
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X1F
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0X0F
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0X07
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0X03
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0X01
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0X00
   MOVWF PORTB
   CALL DELAY2
   DECFSZ INDEX,1
   GOTO F1      
SHADOW                                ;SHADOW EFFECT
SNT
   MOVLW 0X05
   MOVWF INDEX
SL_RUN 
       CLRF PORTB
       BSF STATUS,C
       MOVLW 0XFE
       MOVWF PORTB
       CALL DELAY2
SROT   RLF PORTB,1
       CALL DELAY2
       BTFSC PORTB,7     
       GOTO SROT 
       GOTO SECS
SECS   BCF  STATUS,C
       GOTO SR_RUN
          
SR_RUN
       BSF STATUS,C
       MOVLW 0X7F
       MOVWF PORTB
       CALL DELAY2
SRRT   RRF PORTB,1
       CALL DELAY2
       BTFSC PORTB,0    
       GOTO SRRT 
       GOTO SRCS
SRCS   BCF  STATUS,C
       DECFSZ INDEX,1
       GOTO SL_RUN
       GOTO DOUBLE
       
DOUBLE 
       MOVLW 0X05
       MOVWF INDEX
DD
   MOVLW 0X81
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X42
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X24
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X18
   MOVWF PORTB  
   CALL DELAY2 
   MOVLW 0X24
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X42
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X81
   MOVWF PORTB
   CALL DELAY2
   DECFSZ INDEX,1
   GOTO DD
   GOTO D_FILL
D_FILL
    MOVLW 0X05
    MOVWF INDEX

DF MOVLW 0X00
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X18
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X3C
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X7E
   MOVWF PORTB  
   CALL DELAY2 
   MOVLW 0XFF
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0XE7
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0XC3
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X81
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0X00
   MOVWF PORTB
   CALL DELAY2
   DECFSZ INDEX,1
   GOTO DF
   GOTO REV_FILL
   
REV_FILL

    MOVLW 0X05
    MOVWF INDEX
RF  
   MOVLW 0X81
   MOVWF PORTB
   CALL DELAY2
   MOVLW 0XC3
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XE7
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XFF
   MOVWF PORTB
   CALL DELAY2   
   MOVLW 0XE7
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0XC3
   MOVWF PORTB
   CALL DELAY2 
   MOVLW 0X81
   MOVWF PORTB
   CALL DELAY2
   CLRF PORTB 
   CALL DELAY2
   DECFSZ INDEX,1
   GOTO RF
   GOTO SHIFT
SHIFT
    MOVLW 0X10
    MOVWF INDEX
SS  MOVLW 0XAA
    MOVWF PORTB
    CALL DELAY2
    MOVLW 0X55
    MOVWF PORTB
    CALL DELAY2
    DECFSZ INDEX,1
    GOTO SS 
BLINK
    MOVLW 0X0A
    MOVWF INDEX
BB  CLRF PORTB
    MOVLW 0XFF
    MOVWF PORTB 
    CALL DELAY2
    MOVLW 0X00
    MOVWF PORTB
    CALL DELAY2
    DECFSZ INDEX,1
    GOTO BB
LOAD
 CLRF PORTB
 CALL DELAY2
 MOVLW 0X01
 MOVWF LROOM
 MOVLW 0XFF
 MOVWF HROOM

LD
 MOVLW 0XFF
 MOVWF PORTB
 
 CALL DELAY_PWM1
 CLRF PORTB 
 CALL DELAY_PWM2

MATH
 INCF LROOM,1
 DECF HROOM,1 
 MOVLW 0X00
 MOVWF COMP 
 SUBWF HROOM,0
 BTFSS STATUS,Z
 GOTO LD
LUAD
 MOVLW 0XFF
 MOVWF LROOM
 MOVLW 0X01
 MOVWF HROOM

LE
 MOVLW 0XFF
 MOVWF PORTB
 
 CALL DELAY_PWM1
 CLRF PORTB 
 CALL DELAY_PWM2
BATH
 DECF LROOM,1
 INCF HROOM,1 
 MOVLW 0X00
 MOVWF COMP 
 SUBWF HROOM,0
 BTFSS STATUS,Z
 GOTO LE
 GOTO LVE
 
DELAY_PWM1      
           MOVF LROOM,W        ;DEALY FOR OUT PUT
           MOVWF 0X24
OS2        DECFSZ 0X24,1
           GOTO DELAY2.10
           RETURN 
DELAY2.10  MOVLW 0X10
           MOVWF 0X25
OS1        DECFSZ	0X25,1
		   GOTO OS1	
           GOTO OS2    
                          

DELAY_PWM2      
           MOVF HROOM,W        ;DEALY FOR OUT PUT
           MOVWF 0X26
S2         DECFSZ 0X26,1
           GOTO DELAY2.10
           RETURN 
DELAY2.1   MOVLW 0X10
           MOVWF 0X27
S1         DECFSZ	0X27,1
		   GOTO S1	
           GOTO S2    
           GOTO OS2    
                          
REV       
    
DELAY2      
            MOVLW 0XFF          ;DEALY FOR OUT PUT
            MOVWF 0X3A
OIS2        DECFSZ 0X3A,1
            GOTO IDELAY2.10
            RETURN 
IDELAY2.10  MOVLW 0XFF
            MOVWF 0X3B
OIS1        DECFSZ	0X3B,1
		    GOTO OIS1	
            GOTO OIS2    
                          
      
    END   
